balena-os/balena-intel

CHANGELOG.md
intel-corei7-64.coffee

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-intel/2)

intel-corei7-64.coffee: Promote board to released

---

.gitmodules
layers/meta-resin-intel/conf/samples/bblayers.conf.sample

Switch to docker

---

CHANGELOG.md
layers/meta-resin-intel/conf/samples/local.conf.sample

Connects to resin-os/meta-resin#137-replace-SUPERVISOR-TAG
@telphan @floion @petrosagg

Replace SUPERVISOR_TAG by TARGET_TAG on resin-intel

---

CHANGELOG.md
layers/meta-resin-intel/conf/samples/local.conf.sample

Connects to resin-os/meta-resin#128-debug-image
@telphan @floion @petrosagg

Replace RESIN_STAGING_BUILD by DEBUG_IMAGE on resin-intel

---

.gitmodules
intel-corei7-64.coffee

This implements resin-os/resin-yocto-scripts#31
Signed-off-by: Eugene Mirotin eugene@resin.io
@agherzan @floion

Update to use the simplified JSON building process on resin-intel

---

CHANGELOG.md
intel-corei7-64.coffee

Switch partition with conf in coffee

---

CHANGELOG.md
layers/meta-resin-intel/conf/samples/local.conf.sample

@agherzan @floion 
Connects to resin-os/meta-resin#315

Replace DEBUG_IMAGE with DEVELOPMENT_IMAGE

---

README.md

Connects to contributing
@telphan @floion @michal-mazurek

Add Contributing section on resin-intel

---

CHANGELOG.md

* Update resin-yocto-scripts to fix logging in container builds on resin-intel

---

CHANGELOG.md
intel-corei7-64.coffee
layers/meta-resin-intel/conf/samples/bblayers.conf.sample

Connected to https://github.com/resin-os/resinos/issues/113

Switch NUC to morty

---

CHANGELOG.md
layers/meta-resin-intel/recipes-bsp/grub/files/grub.cfg_external
layers/meta-resin-intel/recipes-bsp/grub/files/grub.cfg_internal
layers/meta-resin-intel/recipes-core/images/resin-image-flasher.bbappend
layers/meta-resin-intel/recipes-core/images/resin-image.inc
layers/meta-resin-intel/recipes-core/initrdscripts/files/init-external-media.sh
layers/meta-resin-intel/recipes-core/initrdscripts/initramfs-live-boot_%.bbappend
layers/meta-resin-intel/recipes-kernel/linux/linux-yocto_%.bbappend
layers/meta-resin-intel/recipes-support/resin-init/resin-init-flasher.bbappend

Connected to https://github.com/resin-os/resinos/issues/149

NVME support

---

CHANGELOG.md
layers/meta-resin-intel/recipes-bsp/grub/files/grub.cfg_external
layers/meta-resin-intel/recipes-bsp/grub/files/grub.cfg_internal
layers/meta-resin-intel/recipes-core/initrdscripts/files/init-external-media.sh

Fixes https://github.com/resin-os/resinos/issues/218

Fix labels

---

CHANGELOG.md
layers/meta-resin-intel/recipes-kernel/linux/linux-yocto_%.bbappend

Connects to resin-os/resinos#246

Enable DLM module for intel NUC

---

CHANGELOG.md
layers/meta-resin-genericx86/recipes-support/hostapp-update-hooks/files/99-flash-grub

Lets only flash grub legacy if we do not support UEFI

hostapp-update-hooks: Conditionally flash grub legacy

---

layers/meta-resin-genericx86/recipes-support/resin-init/resin-init-flasher-board/resin-init-flasher-board

Update meta-resin from v2.15.1 to v2.19.0
Changelog-entry: Update meta-resin from v2.15.1 to v2.19.0

layers/meta-resin: Update to v2.19.0

---

layers/meta-resin-genericx86/recipes-support/resin-init/resin-init-board.bbappend

Changelog-entry: Fix incorrect FILESEXTRAPATHS append

resin-init-board.bbappend: Fix incorrect FILESEXTRAPATHS append

---

README.md

README.md: renamed resin to balena in build script references

---

layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend

Changelog-entry: Enable USB RNDIS driver
Signed-off-by: Zahari Petkov <zahari@balena.io>

linux-yocto_%.bbappend: Enable USB RNDIS driver

---

genericx86-64.coffee
layers/meta-balena-genericx86/conf/layer.conf
layers/meta-balena-genericx86/conf/samples/bblayers.conf.sample

This is a draft PR because it needs merged and released support in meta-balena: https://github.com/balena-os/meta-balena/pull/1351
Tested on:
* RaspberryPi3
* fin3
* Generic X86

Yocto Thud support in balena-intel

---

layers/meta-balena-genericx86/recipes-bsp/efivar/efivar/0001-efivar-fix-for-cross-compile.patch
layers/meta-balena-genericx86/recipes-bsp/efivar/efivar/0004-fix-unknow-option-for-gold-linker.patch
layers/meta-balena-genericx86/recipes-bsp/efivar/efivar/allow-multi-definitions-for-native.patch
layers/meta-balena-genericx86/recipes-bsp/efivar/efivar_37.bb

Update meta-balena from 2.34.1 to 2.35.0
Changelog-entry: Update meta-balena from v2.34.1 to v2.35.0

layers/meta-balena: Update to v2.35.0

---

layers/meta-balena-genericx86/recipes-kernel/linux/files/0002-NFLX-2019-001-SACK-Panic.patch
layers/meta-balena-genericx86/recipes-kernel/linux/files/0004-NFLX-2019-001-SACK-Slowness.patch
layers/meta-balena-genericx86/recipes-kernel/linux/files/0005-NFLX-2019-001-Resour-Consump-Low-MSS.patch
layers/meta-balena-genericx86/recipes-kernel/linux/files/0006-NFLX-2019-001-Resour-Consump-Low-MSS.patch
layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend

ID: NFLX-2019-001
Title: Linux and FreeBSD Kernel: Multiple TCP-based remote denial of service vulnerabilities
Release Date: 2019-06-17
Severity: Critical

Netflix patches

---

surface-go.coffee
surface-pro-6.coffee

Change the state field to 'new'
instead of 'experimental'
Changelog-entry: Change the state to 'new' in the coffee files
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>

coffee: Set state to 'new'

---

genericx86-64-ext.coffee
genericx86-64.coffee
surface-go.coffee
surface-pro-6.coffee

Changelog-entry: Set private to false in .coffee files for the public device types

.coffee: Set private to false for the public device types

---

layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
layers/meta-balena-genericx86/recipes-kernel/linux/surface-go/0101-media-ipu3-cio2-Use-v4l2_get_link_freq-helper.patch
layers/meta-balena-genericx86/recipes-kernel/linux/surface-go/0102-media-v4l-Add-a-helper-for-obtaining-the-link-freque.patch
layers/meta-balena-genericx86/recipes-kernel/linux/surface-go/0103-media-v4l-common-Fix-naming-of-v4l2_get_link_rate.patch
layers/meta-balena-genericx86/recipes-kernel/linux/surface-go/0104-media-ipu3-cio2-Fix-mbus_code-processing-in-cio2_sub.patch
layers/meta-balena-genericx86/recipes-kernel/linux/surface-go/0105-ipu3-cio2-Fix-pixel-rate-derived-link-frequency.patch
layers/meta-balena-genericx86/recipes-kernel/linux/surface-go/0106-media-ipu3-cio2-Toggle-sensor-streaming-in-pm-runtim.patch
layers/meta-balena-genericx86/recipes-kernel/linux/surface-go/0107-media-i2c-Add-support-for-ov5693-sensor.patch
layers/meta-balena-genericx86/recipes-kernel/linux/surface-go/0108-media-i2c-ov5693-add-delays-to-powerdown.patch

This brings in patches as of Apr 16 with
upstream HEAD revision d35c7a1
Changelog-entry: linux-yocto: Bring in new patches for SGO2
Signed-off-by: Alexandru Costache <alexandru@balena.io>

linux-yocto: Bring in new patches for SGO2

---

genericx86-64-ext.coffee

Changelog-entry: Publish both flasher and raw images for Generic x86_64
Signed-off-by: Kyle Harding <kyle@balena.io>

genericx86-64-ext: Publish both flasher and raw images

---

layers/meta-balena-genericx86/recipes-core/images/balena-image-flasher.bbappend
layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend

Changelog-entry: Add support for secure boot and FDE to Generic x86_64
Signed-off-by: Michal Toman <michalt@balena.io>

Add support for secure boot and FDE

---

.github/workflows/build_and_deploy.yml

Changelog-entry: update build and deploy workflow to v0.0.11

github: build_and_deploy: update to v0.0.11

---

.github/workflows/build_and_deploy.yml

Changelog-entry: update build and deploy github workflow to v0.0.12

github: build_and_deploy: update github workflow to v0.0.12

---

layers/meta-balena-genericx86/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner

Update meta-balena from 5.0.11 to 5.0.12
Changelog-entry: Update meta-balena from v5.0.11 to v5.0.12

layers/meta-balena: Update meta-balena to v5.0.12

---

.github/workflows/genericx86-64.yml
.github/workflows/intel-nuc.yml

Adding BalenaOS GitHub action to test on balena-intel repository

Add GHA build and deploy workflows

---

.github/workflows/genericx86-64.yml
.github/workflows/intel-nuc.yml
.github/workflows/surface-go.yml
.github/workflows/surface-pro-6.yml

CI: alter workflow triggers

---

.gitmodules
layers/meta-balena-genericx86/conf/samples/bblayers.conf.sample
layers/meta-balena-genericx86/conf/samples/local.conf.sample

https://balena.fibery.io/Work/Project/balenaos-SBOM-as-release-asset-1515
Changelog-entry: Generate SBOM and VEX (cycloneDX)
Signed-off-by: Edwin Joassart <edwin.joassart@balena.io>

Add CycloneDX SBOM and VEX generation
