- intel-corei7-64.coffee
This makes the instructions use Etcher as primary image burning software.
To make it work: (from @emirotin) 
1. approve and merge resin-io/resin-device-types#7
2. update the resin-device-types submodule in this branch and update this PR
3. test how the JSON file is built (I've tested it myself by checking out the corresponding branch in a submodule)
4. approve and merge this PR
5. follow the standard procedure to release this device type and get it to img-maker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resin-intel/4)
> use etcher instructions

- CHANGELOG.md
- layers/meta-resin-intel/recipes-containers/docker-disk/docker-resin-supervisor-disk.bbappend
Connects to resin-os/meta-resin#133-supervisor-custom-image-tag
@telphan @floion
> Custom docker images in connectable builds on resin-intel

- CHANGELOG.md
- layers/meta-resin-intel/conf/samples/bblayers.conf.sample
Connects to resin-os/meta-resin#404-meta-fs-layer
@telphan @floion @petrosagg @petrosagg @michal-mazurek
> Add meta-filesystem as we need aufs-utils on resin-intel

- CHANGELOG.md
- layers/meta-resin-intel/recipes-bsp/grub/files/grub.cfg_internal
- layers/meta-resin-intel/recipes-core/images/resin-image-flasher.bbappend
- layers/meta-resin-intel/recipes-core/images/resin-image-initramfs.bbappend
- layers/meta-resin-intel/recipes-core/images/resin-image.inc
- layers/meta-resin-intel/recipes-core/initrdscripts/files/labelrootfs
- layers/meta-resin-intel/recipes-core/initrdscripts/initramfs-framework_%.bbappend
Connects to resin-os/meta-resin#379
This PR is incomplete, because it awaits this (resin-os/meta-resin#594) to be merged.
> Integrate old initramfs in the new framework

- CHANGELOG.md
Connected to https://github.com/resin-os/resinos/issues/241
This should fix the issue with the file package failing to build.
> Update poky to the latest morty revision

- CHANGELOG.md
This updates the Poky submodule to the latest morty revision which reverts the previous change to the file package which reflects upstream's decision to put their repo back to how it was before.
> Update Poky submodule

- CHANGELOG.md
- layers/meta-resin-intel/recipes-kernel/linux/linux-yocto_%.bbappend
A user on gitter had an issue with an embedded x86 board that had some extra serial ports that weren't showing up. Increase the number of available serial ports to 32 (this is the value that Fedora uses for their kernel on i686 and x86_64). Also enable console on serial.
> Enable more than four serial ports

- CHANGELOG.md
- layers/meta-resin-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
We need these kernel drivers for bluetooth to work on the Intel NUC when using
the genericx86-64 machine.
> linux-yocto_%.bbappend: Enable kernel drivers needed for bluetooth

- CHANGELOG.md
- layers/meta-resin-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
> linux-yocto_%.bbappend: Enable VXLAN support as a module

- CHANGELOG.md
- layers/meta-resin-genericx86/recipes-bsp/grub/files/grub.cfg_internal-dev
- layers/meta-resin-genericx86/recipes-bsp/grub/files/grub.cfg_internal-prod
Some intel Atom SoCs tend to hang while transitioning to idle states.
See https://bugzilla.kernel.org/show_bug.cgi?id=109051 for one example of such bug report.
Thus we limit to 1 the cstate the CPU can go into.
> grub: Limit CPU cstate to 1

- CHANGELOG.md
- layers/meta-resin-genericx86/conf/samples/local.conf.sample
to RESIN_CONNECTABLE* variables
meta-resin 2.14.0 will allow building of one image which by default is unmanaged.
The conversion between managed and unmanaged will be done through the os-config tool
at boot time, based on the existence of resinio configuration parameters in config.json,
so we remove the references to these obsolete variables from here.
> local.conf.sample: Delete references

- layers/meta-resin-genericx86/recipes-bsp/grub/grub-efi_%.bbappend
We do not need the grub utilities in the rootfs.
Changelog-entry: Do not install grub-common in the rootfs
> grub-efi_%.bbappend: Remove runtime dependency on grub-common

- layers/meta-resin-genericx86/recipes-core/os-config/os-config_%.bbappend
Now meta-resin upgraded UPX to version 3.95 which fixes the segfaults
we have been seeing when compressing os-config on x86 platforms.
Changelog-entry: Re-add UPX compression for os-config
> os-config: Re-add UPX compression

- layers/meta-resin-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: linux-yocto: Activate CONFIG_SND_DYNAMIC_MINORS in kernel
Signed-off-by: Sebastian Panceac <sebastian@resin.io>
> linux-yocto: Activate CONFIG_SND_DYNAMIC_MINORS in kernel

- layers/meta-resin-genericx86/recipes-kernel/linux/files/0002-Revert-random-fix-crng_ready-test.patch
- layers/meta-resin-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
The introduction of this patch caused balena to start with a delay
because not enough entropy is gathered by the time balena starts.
Changelog-entry: Revert "random: fix crng_ready() test" to fix balena delay start issue
> linux-yocto_%.bbappend: Revert "random: fix crng_ready() test" patch

- layers/meta-resin-genericx86/recipes-support/usb-modeswitch/files/usb_modeswitch_avoid_coredump.patch
- layers/meta-resin-genericx86/recipes-support/usb-modeswitch/usb-modeswitch_2.5.0.bbappend
On 64 bits platforms (generic Intel x86-64, NVidia Jetson TX2),
the systemd usb-modeswitch service will core dump when starting.
Changelog-entry: Workaround for usb_modeswitch crash on 64 bits platforms
> usb-modeswitch_2.5.0.bbappend: Work around usb_modeswitch crash

- layers/meta-resin-genericx86/recipes-bsp/grub/files/grub.cfg_internal_template
At this point we need to figure out more scenarios that would trigger
a reboot before healthcheck actually runs (such as supervisor triggered
reboots).
Such an early reboot is not an indication of a hostOS update failure and
so we do not wish for rollbacks to take place in these scenarios.
Until all corner cases are discussed and handled in the OS, we disable
rollback functionality.
Changelog-entry: Temporarily disable rollback functionality
> grub: Temporarily disable rollbacks

- layers/meta-resin-genericx86/recipes-support/resin-init/resin-init-board.bbappend
- layers/meta-resin-genericx86/recipes-support/resin-init/resin-init-board/resin-init-board
It's been observed on EFI machines that at the first boot after
provisioning there is some bootstrap code in the first sector of
the boot media (even though during provisioning we make sure we
remove this bootstrap code). In such a case (only on some machines),
the next time we reboot the machine, it will not recognize the media
as a valid EFI boot media and the boot will fail.
Changelog-entry: Add script to ensure correct future EFI boot
> resin-init-board: Add script to ensure correct future EFI boot

- layers/meta-resin-genericx86/recipes-core/images/resin-image-flasher.bbappend
- layers/meta-resin-genericx86/recipes-core/images/resin-image.inc
- layers/meta-resin-genericx86/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner
It's been observed on EFI machines that at the first boot after
provisioning there is some bootstrap code in the first sector of
the boot media (even though during provisioning we make sure we
remove this bootstrap code). In such a case (only on some machines),
the next time we reboot the machine, it will not recognize the media
as a valid EFI boot media and the boot will fail.
Changelog-entry: Make hostapp-update-hooks clean-up legacy grub to ensure correct future EFI boot
> hostapp-update-hooks:999-resin-boot-cleaner: Clean-ups for EFI

- layers/meta-resin-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: Enable TULIP driver for Hyper-V
> linux-yocto_%.bbappend: Enable TULIP driver for Hyper-V

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
As requested by customer
Changelog-entry: Build ACPI_WMI kernel module as requested by customer
> linux-yocto_%.bbappend: Enable ACPI_WMI

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: Fix typo that prevented microSD card support for Microsoft Surface Go
> linux-yocto_%.bbappend: Fix typo

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
When TPM 2.0 support is present, the following devices
are available:
/dev/tpm0
/dev/tpmrm0
Changelog-entry: Added TPM kernel module support
Signed-off-by: Vicentiu Galanopulo <vicentiu@balena.io>
> linux-yocto_%.bbappend: Add CONFIG options for TPM

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: Enable the AD5593R driver
> linux-yocto: Enable the AD5593R driver

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Some boards only support SATA IDE mode (no AHCI) so in order to boot
correctly without adding the ata_piix kernel module in the rootfs we
make the driver as built-in.
Changelog-entry: Set ATA_PIIX as built-in so we can boot legacy IDE mode without adding the ata_piix driver in the initramfs
> linux-yocto: Set ATA_PIIX as built-in

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Requested by customer
Changelog-entry: Enable PINCTRL_BAYTRAIL support in the kernel
> linux-yocto_%.bbappend: Enable PINCTRL_BAYTRAIL

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: Enable USB Winchiphead CH341 Single Port Serial Driver
> linux-yocto: Enable USB Winchiphead CH341 Single Port Serial Driver

- layers/meta-balena-genericx86/recipes-kernel/linux/files/0007-BUGFIX-iwlwifi-mvm-Allow-multicast-~ta-frames-only-when-associated.patch
- layers/meta-balena-genericx86/recipes-kernel/linux/files/0008-BUGFIX-iwlwifi-mvm-Allow-multicast-~ta-frames-only-when-authorized.patch
- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
These patches fix the following issue related to multicast frames:
Unhandled alg: 0x707
Changelog-entry: Backport iwlwifi patches for multicast frames handling
> linux-yocto: Backport iwlwifi patches for multicast frames

- layers/meta-balena-genericx86/recipes-support/resin-init/resin-init-flasher-board/resin-init-flasher-board
In newer OS images, when the flasher runs, the efivarfs
is already mounted and this makes the flasher script error out.
Let's make sure we run the mount command only if efivarfs is not
already mounted.
Changelog-entry: Only mount efivarfs in flasher if it's not already mounted
> resin-init-flasher-board: Conditionally mount efivarfs

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
We switched to kernel 5.0.3 and by default this kernel lacks
DESIGNWARE I2C support.
This is needed to fix missing /dev/sri/card0 on Intel Atom
Cherry Trail based boards.
Changelog-entry: Enable I2C support on kernel 5.x for Intel Atom Cherry Trail based SoCs
> linux-yocto: Enable I2C on Intel Atom Cherry Trail based SoCs

- layers/meta-balena-genericx86/recipes-bsp/grub/grub-conf/grub.cfg_internal_template
This PR assumes support in `meta-balena`: https://github.com/balena-os/meta-balena/pull/1677
After first boot, the OS will generate the UUID of every partition and
store their values in a boot partition file. Source this file and pass
these UUIDs, when available, as part of cmdline so that the OS can use
them for partition mounts.
Changelog-entry: Pass partitions UUID in cmdline when available
Signed-off-by: Andrei Gherzan <andrei@balena.io>
> grub-conf: Include in cmdline partitions UUID when available

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: Enable HFS drives support
> linux-yocto_%.bbappend: Enable HFS drives support

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: Enable the ixgbe driver for the genericx86-64 machine
> linux-yocto: Enable ixgbe driver for genericx86-64

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: Enable the xillybus pcie driver for the genericx86-64 machine
> linux-yocto: Enable xillybus pcie driver for genericx86-64

- layers/meta-balena-genericx86/recipes-support/resin-init/resin-init-flasher-board/resin-init-flasher-board
When installing UEFI grub, it is better to use fdisk to check that
an internal media is a suitable block device rather than using
the shell internal block testing feature. This is because there
is at least a case when the kernel lists an ASMT 2115 controller
as /dev/sda but that is not an actual drive so it cannot be
written to and the flashing procedure will error out.
Changelog-entry: Tweak how the flasher asserts that internal media is valid for being installed UEFI grub on
> resin-init-flasher-board: Tweak detection of internal media

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Requested by customer for the genericx86-64 machine
Changelog-entry: Enable the i40e kernel driver for the genericx86-64 machine
> linux-yocto_%.bbappend: Enable the i40e kernel driver

- layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
- layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_git.bbappend
> Add linux-firmware-iwlwifi-3168 to support wifi adapters for older NUCs

- layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
Changelog-entry: Add firmware for Intel wifi chipset on NUC 10th gen
> linux-firmware: Add firmware for Intel wifi chipset on NUC 10th gen

- layers/meta-balena-genericx86/recipes-kernel/linux/files/0001-ovl-fix-regression-caused-by-overlapping-layers-dete.patch
- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Changelog-entry: Backport the "ovl: fix regression caused by overlapping layers detection" patch
> linux-yocto: Backport overlay regression fix

- layers/meta-balena-genericx86/recipes-bsp/grub/grub-conf/grub.cfg_internal_template
- layers/meta-balena-genericx86/recipes-bsp/grub/grub-efi_%.bbappend
- layers/meta-balena-genericx86/recipes-core/images/resin-image.inc
Some background.
This PR is related to https://github.com/balena-os/meta-balena/pull/1840
* Modifies resin-init-flasher to give preference to by-state labels
* Modifies grub config to select the root partition from the same drive grub booted from
> grub-conf: Boot using filesystem UUIDS instead of labels

- layers/meta-balena-genericx86/recipes-bsp/grub/grub-conf.bb
- layers/meta-balena-genericx86/recipes-bsp/grub/grub-conf/grub.cfg_external
- layers/meta-balena-genericx86/recipes-bsp/grub/grub-conf/grub.cfg_internal_template
- layers/meta-balena-genericx86/recipes-core/images/resin-image.inc
This adds support for GRUB extra command line arguments using a grub_extraenv file in the boot partition
> Add grub extra_os_cmdline support

- layers/meta-balena-genericx86/conf/image-uefi.conf
- layers/meta-balena-genericx86/recipes-bsp/grub/files/0001-Disable-mfpmath-sse-as-well-when-SSE-is-disabled.patch
- layers/meta-balena-genericx86/recipes-bsp/grub/files/0001-grub.d-10_linux.in-add-oe-s-kernel-name.patch
- layers/meta-balena-genericx86/recipes-bsp/grub/files/autogen.sh-exclude-pc.patch
- layers/meta-balena-genericx86/recipes-bsp/grub/files/cfg
- layers/meta-balena-genericx86/recipes-bsp/grub/files/grub-module-explicitly-keeps-symbole-.module_license.patch
- layers/meta-balena-genericx86/recipes-bsp/grub/grub-bootconf_1.00.bb
- layers/meta-balena-genericx86/recipes-bsp/grub/grub-efi_2.04.bb
- layers/meta-balena-genericx86/recipes-bsp/grub/grub2.inc
- layers/meta-balena-genericx86/recipes-bsp/grub/grub_2.04.bb
Until we support dunfell-23.0.1 we need to use a newer grub version 2.04
needed for example by Dell Latitude 7220 Rugged Extreme Tablet.
Changelog-entry: Update to grub 2.04 taken from Poky dunfell-23.0.1
> grub: Add recipe version 2.04 from Poky dunfell-23.0.1

- layers/meta-balena-genericx86/recipes-support/resin-init/resin-init-board.bbappend
- layers/meta-balena-genericx86/recipes-support/resin-init/resin-init-board/surface-go-init-board
This adds the steps for initializing the LTE modem
on the Surface Go tablet. By default rx_max and tx_max
are 16384, however this sequence is needed to bring
up the modem.
Changelog-entry: resin-init-board: Add Surface Go LTE modem initialization
Signed-off-by: Alexandru Costache <alexandru@balena.io>
> resin-init-board: Add Surface Go LTE modem initialization

- layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-resin.bbappend
- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Add support for aufs in addition to overlay2 for Generic x86-64
Depends-on: https://github.com/balena-os/meta-balena/pull/2132
Changelog-entry: Add support for aufs in addition to overlay2 for Generic x86-64
Signed-off-by: Kyle Harding <kyle@balena.io>
> genericx86-64-ext: Add support for aufs in addition to overlay2

- genericx86-64-ext.coffee
- genericx86-64.coffee
- layers/meta-balena-genericx86/conf/samples/local.conf.sample
- layers/meta-balena-genericx86/recipes-core/images/balena-image-flasher.bbappend
- layers/meta-balena-genericx86/recipes-core/images/balena-image.bbappend
- layers/meta-balena-genericx86/recipes-core/images/balena-image.inc
- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto-rt_%.bbappend
- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
- layers/meta-balena-genericx86/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner
- smartcube-kbox-a150.coffee
- smartcube-kbox-a250.coffee
- surface-go.coffee
- surface-pro-6.coffee
As part of a full rename away from legacy resin namespaces the
following device compatibility changes are required to align
with meta-balena changes.
- update coffee files
- rename bbappend files
- bulk rename of RESIN_ variables
Change-type: minor
Changelog-entry: Rename resin image types to balena
Depends-on: balena-os/meta-balena#2118, balena-os/balena-yocto-scripts#184
Signed-off-by: Kyle Harding <kyle@balena.io>
> balena-intel: rename resin image types to balena

- layers/meta-balena-genericx86/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner
Replace all references to the 'resin-vars' script with 'balena-config-vars' as it has been renamed.
This PR needs to be merged when https://github.com/balena-os/meta-balena/pull/2142 has been merged.
Changelog-entry: balena-intel: replace references to resin-vars
Signed-off-by: Mark Corbin <mark@balena.io>
> balena-intel: replace references to resin-vars

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
meta-balena includes support for overlayfs as of 2.76.0
Connects-to: https://github.com/balena-os/meta-balena/pull/2169
Signed-off-by: Robert Günzler <robertg@balena.io>
> linux: drop forcing overlayfs support into a module

- layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
This package already exists in linux-firmware_20190815.bb and upstream.
> remove redundant bcm43455 firmware package

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
This driver is required for the I225-LM Ethernet Controller present on
the Intel NUC 11th generation.
Changelog-entry: Enable the igc driver for the Intel NUC 11 I225-LM Ethernet Controller
> linux-yocto: Enable the igc driver

- layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Package this instead in meta-balena, allowing other x86 DTs to use it.
Requires: https://github.com/balena-os/meta-balena/pull/2267
> linux-firmware: remove linux-firmware-i915-kbl package

- layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
- layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
We add this fw on its own package so that boards can add it to
rootfs (for Intel NUC 11th generation more specifically)
Changelog-entry: Package iwlwifi-QuZ-a0-hr-b0 firmware separately
> linux-firmware: Package iwlwifi-QuZ-a0-hr-b0 firmware

- layers/meta-balena-genericx86/conf/machine/smartcube-kbox-a150.conf
- layers/meta-balena-genericx86/conf/machine/smartcube-kbox-a250.conf
- layers/meta-balena-genericx86/conf/samples/local.conf.sample
- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
The customer that requested these device types never really used them so
let's remove all references to them from here.
Changelog-entry: Remove references to unused Smartcube device types
> smartcube: Remove reference to these obsolete machines

- layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
Upstream firmware is now compatible with the Surface Go, and the old
firmware is incompatible with other common devices. Default to the
upstream firmware to resolve these issues.
This reverts commit d50848e
This branch requires the linux-firmware-20210511 PR from meta-balena: https://github.com/balena-os/meta-balena/pull/2240
> linux-firmware: use upstream for ath10k/QCA6174

- layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
This installs upstream firmware for the QCA6174 802.11ac adapter.
> add linux-firmware-ath10k-qca6174 to connectivity firmware

- layers/meta-balena-genericx86/conf/machine/genericx86-64-ext.conf
- layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
Make use of the firmware compression support in meta-balena to update to the latest version of linux-firmware
> Use firmware compression for genericx86-64-ext

- genericx86-64-ext.coffee
Reverts balena-os/balena-intel#414
Reverting this for now until we have the full solution ready. We don't want to accidentally publish the non-flasher images early.
Improvement: https://jel.ly.fish/improvement-expose-flasher-raw-images-dashboard-generic-dts-90f2f44
> Revert "genericx86-64-ext: Publish both flasher and raw images"

- layers/meta-balena-genericx86/conf/samples/local.conf.sample
There are two reasons for this patch:
1. The current flag is incorrect, see https://github.com/balena-os/meta-balena/blob/master/README.md#os-development
2. The `barys` script will not work when `--development` is used, see https://github.com/balena-os/balena-yocto-scripts/blob/master/build/barys#L449 and https://github.com/balena-os/balena-yocto-scripts/issues/251
> Rename `DEVELOPMENT_IMAGE` flag to `OS_DEVELOPMENT` 

- layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
The PR depends on https://github.com/balena-os/meta-balena/pull/2239
These adapters are on 10th and 11th gen NUCs, recent laptops and also available as standalone M.2 cards.
- AX200NGW: iwlwifi-cc-a0 and ibt-20-1-3
- AX201NGW: iwlwifi-quz-a0-hr-b0 and ibt-19-0-4
Changelog-entry: Include firmware for AX200NGW and AX201NGW WiFi 6 adapters
Signed-off-by: Michal Toman <michalt@balena.io>
> linux-firmware: Include firmware for AX200NGW and AX201NGW WiFi 6 adapters

- layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
This allows the package to be used by other device types.
The corresponding meta-balena change is https://github.com/balena-os/meta-balena/pull/2239/files
Changelog-entry: Move iwlwifi-quz-a0-hr-b0 firmware to meta-balena
> linux-firmware: Move iwlwifi-quz-a0-hr-b0 to meta-balena

- layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
This is necessary to unwind a circular dependency moving the package to meta-balena
> packagegroup-balena-connectivity: Remove redundant linux-firmware-iwlwifi-quz-a0-hr-b0

- genericx86-64-ext.coffee
Now that balena-yocto-scripts support uploading named artifacts, upload
raw and flasher images for genericx86-64-ext.
> genericx86-64-ext: add raw and flasher artifacts

- genericx86-64-ext.coffee
As we're introducing another generic x86_64 device type with the slug
generic-amd64 that introduces GPT partitioning, add a qualifier to the
existing device type's long name that indicates that it's both legacy,
and uses MBR partitioning.
> genericx86-64-ext: qualify visible name w/ legacy MBR

- layers/meta-balena-genericx86/conf/layer.conf
We use the genericx86-64 machine configuration file from Poky which would
be the preferred place for this setting to be in.
Changelog-entry: Add firmware compression for Intel NUC
> Add firmware compression for Intel NUC and surface go

- layers/meta-balena-genericx86/recipes-core/packagegroups/packagegroup-balena-connectivity.bbappend
These are used for AX201NGW and AC9462 respectively, available on 11th gen NUCs as well as standalone M.2 cards.
Depends-on: https://github.com/balena-os/balena-intel/pull/532
> balena-connectivity: Include iwlwifi-quz-a0-hr-b0 and iwlwifi-quz-a0-jf-b0

- layers/meta-balena-genericx86/conf/samples/bblayers.conf.sample
Yocto classes and conf files ignore layer priorities and are parsed
in order instead.
Changelog-entry: Modify layer ordering
> bblayers: Modify layer ordering

- layers/meta-balena-genericx86/recipes-kernel/linux/linux-yocto_%.bbappend
This allows to use user space application to access and modify monitor
settings via the Virtual Control Panel and Monitor Control Command Set
accessible via I2C interfaces.
Fixes #545
Changelog-entry: Add I2C character device kernel module
> linux-yocto: Add I2C character device

- layers/meta-balena-genericx86/recipes-kernel/linux-firmware/linux-firmware_%.bbappend
The git protocol has now been deprecated by github.
Changelog-entry: use https protocol for linux-firmware fetch
> linux-firmware: Use https protocol on fetch

- layers/meta-balena-genericx86/conf/machine/genericx86-64-ext.conf
Newer versions of meta-balena use the efi and raid machine features to add user space support.
Changelog-entry: add efi and raid machine features to genericx86-64-ext
> machine: genericx86-64-ext: add efi and raid machine features

- layers/meta-balena-genericx86/recipes-support/hostapp-update-hooks/files/999-resin-boot-cleaner
This prevents the following error and hup abort when sysfs is bind-mounted in the hostapp-update container:
mount: /sys/firmware/efi/efivars: efivarfs already mounted or mount point busy.
Needs to be tested along https://github.com/balena-os/meta-balena/pull/3194
> hostapp-update-hooks: Don't fail if efivars fs already mounted

- layers/meta-balena-genericx86/recipes-kernel/rtl8812au/rtl8812au_5.1.5.bb
The git ref used for the Realtek 802.11n WLAN Adapter Linux driver was deprecated, and to build successfully needed to be updated to an updated ref
> recipes-kernel: update git ref of 8812au driver

- layers/meta-balena-genericx86/recipes-core/images/balena-image-initramfs.bbappend
to make some free space in the rootfs. The NUC image should not be used as a target for migration anyway
Changelog-entry: balena-image-initramfs: Remove migrate module for Intel NUC
Internal thread: https://balena.zulipchat.com/#narrow/stream/345889-balena-io.2Fos/topic/os-config.20update/near/449287399
> balena-image-initramfs: Remove migrate module for Intel NUC

- .github/workflows/genericx86-64.yml
- .github/workflows/surface-go.yml
- .github/workflows/surface-pro-6.yml
See https://balena.fibery.io/Work/Improvement/Make-a-checklist-to-mark-a-repository-BTD-certified-1965
> Add workflows for Surface Go and Surface Pro 6

- .github/workflows/genericx86-64.yml
- .github/workflows/intel-nuc.yml
- .github/workflows/surface-go.yml
- .github/workflows/surface-pro-6.yml
Required for merge (in order):
PR should merge automatically if not marked as draft.
> Update GHA workflow deploy environment to production

- .github/workflows/genericx86-64.yml
- .github/workflows/intel-nuc.yml
- .github/workflows/surface-go.yml
- .github/workflows/surface-pro-6.yml
- layers/meta-balena-genericx86/recipes-kernel/rtl8812au/rtl8812au_5.1.5.bb
Includes a patch for CVE-2024-6387 and updates balena-supervisor to v16.4.1
Changelog-entry: Update meta-balena from v5.2.10 to v5.2.12
See: https://balena.zulipchat.com/#narrow/stream/403752-channel.2Fsupport-help/topic/Supervisor.20ipv4.2Bipv6.20state/near/467486264
See: https://balena.zendesk.com/agent/tickets/3576
> Update meta-balena from 5.2.10 to 5.2.12

- .github/workflows/genericx86-64.yml
- .github/workflows/intel-nuc.yml
- .github/workflows/surface-go.yml
- .github/workflows/surface-pro-6.yml
This flag was left commented out by mistake before the feature was exposed by the yocto workflow.
Changelog-entry: Enable force-finalize flag for manual workflow dispatch
> Enable force-finalize flag for manual workflow dispatch
